development:
  database: &common
    host: 'localhost'
    un:   'root'
    pw:   'tuonela'
    db:   'pibi'

test:
  database:
    <<: *common
    db: 'pibi_test'

production:
  database:
    <<: *common
    db: 'pibi_production'
